// <auto-generated />
using System;
using ITSolution.Framework.Servers.Core.FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITSolution.Framework.Servers.Core.FirstAPI.Migrations
{
    [DbContext(typeof(DbAccessContext))]
    [Migration("20210901170409_Initial_Api")]
    partial class Initial_Api
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ITSolution.Framework.Core.BaseClasses.CommonEntities.ApplicationMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionController")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuPai")
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMenu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ITS_MENU");
                });
#pragma warning restore 612, 618
        }
    }
}
