# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  coreCommon: '**/Common/ITSolution.Framework.Core/ITSolution.Framework.Core.csproj'
  coreServer: '**/Servers/ITSolution.Framework.Server.Core/ITSolution.Framework.Core.Server.csproj'

steps:
- task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$coreCommon'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$coreServer'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '4'
    includeSymbols: true

